[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && rm -rf node_modules package-lock.json",
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "npm start"