[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
    "npx prisma generate",
    "cd frontend && npm install && npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3001"