[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --production=false",
  "cd backend && npm install",
  "cd frontend && rm -rf node_modules package-lock.json",
  "cd frontend && npm install --no-optional"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && npm install @rollup/rollup-linux-x64-gnu --save-dev",
  "cd frontend && npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_VERSION = "20.19.0"