[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"

[[services]]
name = "backend"
source = "."

[services.build]
buildCommand = "npm run build && cd frontend && npm ci && npm run build"

[services.deploy]
startCommand = "npm start"

[[services.variables]]
name = "NODE_ENV"
value = "production"

[[services.variables]]
name = "PORT"
value = "3001"